### PR TITLE
Update to latest version of purgecss plugin

### PR DESCRIPTION
**Pull request by chood531**
I am trying to get this issue pulled into my project so would like to update the purgecss plugin version: https://github.com/FullHuman/purgecss/issues/92

### CODE REVIEW

**Comment by freekmurze** [comment]
Tests seem to be failing for this one.

**Comment by chood531** [comment]
@freekmurze - unfortunately, the tests are also failing on master.

I tried to fix, but can't seem to figure it out.  Seems to be something with Jest.

I updated the version of Jest to fix one issue (https://github.com/facebook/jest/issues/6766#issuecomment-412516712), but that introduced another issue.

Sorry I couldn't help try to fix it.  Couldn't seem to figure it out on my end :(

**Comment by freekmurze** [comment]
No worries, we'll take a look at this soon.

**Comment by sebastiandedeyne** [comment]
I'll look into this soon. Gonna hold off merging a major version update of Purgecss until we've ensured it all works as intended.

**Comment by sebastiandedeyne** [comment]
Ended up merging #49 for this because it solved the test issues, thanks for your time either way!

**Pull request closed without merging**
